# Generated by Django 4.0.3 on 2022-04-30 10:31

from django.db import migrations, models
import main.models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=300)),
                ('course', models.CharField(choices=[('backend', 'Backend with Django'), ('frontend', 'Frontend with React'), ('datascience', 'Data science with Python')], max_length=300)),
                ('bio', models.TextField()),
                ('student_num', models.IntegerField(default=main.models.get_stu_num, editable=False)),
                ('date_joined', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['-date_joined'],
            },
        ),
    ]
